select * from customers;

select * from order_items;
select * from orders;
select * from products;

-- Find the top 5 customers who spent the most money in total, along with:
-- Their total spent (sum of all completed orders)
-- Their number of orders
-- Their average order value
-- Sort by total spent descending and exclude cancelled or pending orders.

select c.customer_id,
c.name,
count(order_id) as num_of_orders,
sum(o.total_amount) as total_spend,
avg(o.total_amount) as avg_order_value
from customers as c
join orders as o
on c.customer_id = o.customer_id
where o.status = 'Completed'
group by
c.customer_id,
c.name
order by sum(o.total_amount) desc
limit 5;


-- Find the average total_amount per order for each country, only for completed orders.
-- Sort by average order value descending.

select
c.country,
avg(o.total_amount) as avg_order
from customers as c
join orders as o
on c.customer_id = o.customer_id
where o.status = 'Completed'
group by
c.country
order by avg_order desc;


-- Find the product name and total quantity sold for the product with the highest total quantity sold (across all orders).

select
p.name,
sum(oi.quantity) as total_quantity_sold
from customers as c
join orders as o
on c.customer_id = o.customer_id
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id
where o.status = 'Completed'
group by p.name
;


-- Show the total revenue per month (from completed orders only) in 2023.

select 
month(order_date) as months,
sum(total_amount) as total_rev
from orders
where status = 'Completed' and year(order_date) = 2023
group by month(order_date)
order by total_rev desc;


-- Find customers who placed more than 2 completed orders.

select
c.customer_id,
c.name,
count(order_id) as count_orders
from customers as c
join orders as o
on c.customer_id = o.customer_id
where o.status = 'Completed'
group by
c.customer_id,
c.name
having count(order_id) >=2
order by count_orders desc;


-- Show the total revenue generated by each product category, ordered by total revenue descending.

select 
p.category,
sum(o.total_amount) as total_rev
from customers as c
join orders as o
on c.customer_id = o.customer_id
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id
group by p.category
order by total_rev desc;
